FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all necessary files
COPY app.py .
COPY preprocess.py .

# Copy the model directory
COPY model/ ./model/
COPY model_docs/ ./model_docs/

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
